- id: jac-format
  name: jac-format
  description: Format Jac files with consistent code style
  entry: jac format
  language: python
  types: [file]
  files: \.jac$
  require_serial: true

- id: jac-check
  name: jac-check
  description: Type check Jac files
  entry: jac check
  language: python
  types: [file]
  files: \.jac$
  require_serial: true
