from __future__ import annotations

print(5 > 4)
print(5 >= 5)
print(3 < 10)
print(3 <= 3)
print(5 == 5)
print(5 != 3)
a = [1, 2, 3]
b = [1, 2, 3]
c = a
print(a is b)
print(a is c)
print(a is not b)
print(3 in a)
print(5 in a)
print(5 not in a)
print(True and True)
print(True and False)
print(False and False)
print(True or False)
print(False or False)
print(True or True)
print(not True)
print(not False)
x = 15
print(10 < x < 20)
print(0 <= x <= 100)
print(x > 20 or x < 5)
print(5 > 3 and 10 < 20)
print(5 > 10 or 3 < 7)
print(not 5 > 10)
print(1 < 2 < 3 < 4)
print(10 >= 10 >= 10)
print(True and True and True)
print(False or False or True)
print(True and False or (False and True))
