import from byllm.llm { Model }
import time;

glob llm = Model(model_name="gpt-4o");

node Task {
    has task:str = "";
    has date:str = "";
    has time:str = "";
}

node TaskHandling {
    def get_current_time() -> str {
        return time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime());
    }
    def add_task(task: str, date: str, time: str) -> str {
        task_created = Task(task=task, date=date, time=time);
        self ++> task_created;
        return "Task added successfully";
    }
    def check_scheduled_tasks -> list[Task] {
        self ++> Task(
            task="Check scheduled tasks",
            date="2025-10-10",
            time="10:00:00"
        ); # Add a sample task for demonstration
        return [self --> (`?Task)];
    }
    def extract_task_info(utterance: str) -> str by llm(
        method="ReAct",
        tools=([self.add_task, self.get_current_time])
    );
    def summarize_tasks() -> str by llm(
        method="ReAct",
        tools=([self.check_scheduled_tasks])
    );
    def route_and_run(utterance: str) -> str by llm(
        method="ReAct",
        tools=([self.extract_task_info, self.summarize_tasks])
    );
    can execute with task_manager entry {
        print("[TaskHandling Node Activated]");
        response = self.route_and_run(visitor.utterance);
        print("→", response);
        report {
            "utterance": visitor.utterance,
            "response": response,
            "node_type": self.__class__.__name__
        };
    }
}

node EmailHandling {
    def write_email_content(utterance: str) -> str by llm();
    def route_and_run(utterance: str) -> str by llm(
        method="ReAct",
        tools=([self.write_email_content])
    );
    can execute with task_manager entry {
        print("[EmailHandling Node Activated]");
        response = self.route_and_run(visitor.utterance);
        print("→", response);
        report {
            "utterance": visitor.utterance,
            "response": response,
            "node_type": self.__class__.__name__
        };
    }
}

node GeneralChat {
    def chat(utterance: str) -> str by llm();
    can execute with task_manager entry {
        print("[GeneralChat Node Activated]");
        response = self.chat(visitor.utterance);
        print("→", response);
        report {
            "utterance": visitor.utterance,
            "response": response,
            "node_type": self.__class__.__name__
        };
    }
}

enum RoutingNodes{
    TASK_HANDLING,
    EMAIL_HANDLING,
    GENERAL_CHAT
}

walker task_manager {
    has utterance: str = "";

    def route_to_node(utterance: str) -> RoutingNodes by llm();
    can execute with `root entry {
        routed_node_name = self.route_to_node(self.utterance);

        if routed_node_name == RoutingNodes.TASK_HANDLING {
            
        } elif routed_node_name == RoutingNodes.EMAIL_HANDLING {
            routed_node = here ++> EmailHandling();
        } elif routed_node_name == RoutingNodes.GENERAL_CHAT {
            routed_node = here ++> GeneralChat();
        }
        visit routed_node;
    }
}
