
import { defineConfig } from 'vite';

export default defineConfig({
    // Use an absolute path for the root if running Vite from a different directory
    // or just rely on the temp directory being the CWD.
    build: {
        outDir: 'dist',         // Output directory relative to the project root (temp_dir)
        emptyOutDir: true,
        minify: false,
        sourcemap: true,
        lib: {
            entry: 'main_entry.js', // The wrapper file generated by the orchestrator
            name: 'JacClient',
            fileName: 'client',
            formats: ['es'],        // We are targeting modern ES modules
        }
    },
});
